# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.synced_folder "~/github/bitcoin", "/home/bitcoin", type: "rsync",
  rsync__args: ["--verbose", "--archive", "--delete", "--compress"],
  rsync__exclude: [".vscode", "depends/built/", "depends/work/", 
                    "depends/x86_64-apple-darwin*", "db4/", "*.o", 
                    "*.a", "*.log", "*.Po", ".lo"]

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--clipboard", "disabled"]
    vb.customize ["modifyvm", :id, "--draganddrop", "disabled"]
    vb.customize ["modifyvm", :id, "--recording", "off"]
    vb.gui = false
    vb.memory = 4096
  end

  config.vm.define "openbsd64" do |box|
    box.vm.box = "generic/openbsd6"

    box.vm.provision "shell" do |s|
      s.path = "openbsd.sh"
      s.name = "Setup"
      s.args = ["setup"]
    end
    box.vm.provision "shell", run: "always" do |s|
      s.path = "openbsd.sh"
      s.name = "Compile"
      s.args = ["compile"]
    end
  end

  config.vm.define "debian-stretch" do |box|
    box.vm.box = "debian/stretch64"

    box.vm.provision "shell" do |s|
      s.path = "debian.sh"
      s.name = "Setup"
      s.args = ["setup"]
    end
    box.vm.provision "shell", run: "always" do |s|
      s.path = "debian.sh"
      s.name = "Compile"
      s.args = ["compile"]
    end
  end

  config.vm.define "travis-linux-no-depends-qt" do |box|
    box.vm.box = "generic/ubuntu1804"

    box.vm.provision "shell" do |s|
      s.path = "travis.sh"
      s.name = "Setup"
      s.args = ["setup"]
    end
    box.vm.provision "shell", run: "always" do |s|
      s.path = "travis.sh"
      s.name = "Compile"
      s.args = ["compile"]
    end
  end

  config.vm.define "freebsd112" do |box|
    box.vm.box = "freebsd/FreeBSD-11.2-STABLE"
    box.ssh.shell = "sh"
    box.vm.synced_folder ".", "/vagrant", disabled: true

    box.vm.provision "shell" do |s|
      s.path = "freebsd.sh"
      s.name = "Setup"
      s.args = ["setup"]
    end
    box.vm.provision "shell", run: "always" do |s|
      s.path = "freebsd.sh"
      s.name = "Compile"
      s.args = ["compile"]
    end
  end

  config.vm.define "freebsd120" do |box|
    box.ssh.shell = "sh"
    box.vm.box = "freebsd/FreeBSD-12.0-RELEASE"
    box.vm.box_version = "2018.12.07"
    box.vm.synced_folder ".", "/vagrant", disabled: true

    box.vm.provision "shell" do |s|
      s.path = "freebsd.sh"
      s.name = "Setup"
      s.args = ["setup"]
    end
    box.vm.provision "shell", run: "always" do |s|
      s.path = "freebsd.sh"
      s.name = "Compile"
      s.args = ["compile"]
    end
  end

  config.vm.define "netbsd8" do |box|
    box.vm.box = "generic/netbsd8"

    box.vm.provision "shell" do |s|
      s.path = "netbsd.sh"
      s.name = "Setup"
      s.args = ["setup"]
    end
    box.vm.provision "shell", run: "always" do |s|
      s.path = "netbsd.sh"
      s.name = "Compile"
      s.args = ["compile"]
    end
  end
end
