# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 6
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--clipboard", "disabled"]
    vb.customize ["modifyvm", :id, "--draganddrop", "disabled"]
    vb.customize ["modifyvm", :id, "--recording", "off"]
    vb.gui = false
    vb.memory = 4096
  end

  config.vm.define "openbsd64" do |box|
    box.vm.box = "generic/openbsd6"

    box.vm.provision "shell" do |s|
      s.path = "openbsd.sh"
      s.name = "Provision"
      s.args = ["provision"]
    end
    box.vm.provision "shell", run: "always" do |s|
      s.path = "openbsd.sh"
      s.name = "Setup"
      s.args = ENV['PR'] ? ["setup", ENV['PR']] : ["setup"]
    end
  end

  config.vm.define "freebsd112" do |box|
    box.vm.box = "freebsd/FreeBSD-11.2-STABLE"
    box.ssh.shell = "sh"
    box.vm.synced_folder ".", "/vagrant", disabled: true

    box.vm.provision "shell" do |s|
      s.path = "freebsd.sh"
      s.name = "Provision"
      s.args = ["provision"]
    end
    box.vm.provision "shell", run: "always" do |s|
      s.path = "freebsd.sh"
      s.name = "Compile"
      s.args = ["compile"]
    end
  end

  config.vm.define "freebsd120" do |box|
    box.ssh.shell = "sh"
    box.vm.box = "bento/freebsd-12"
    box.vm.synced_folder ".", "/vagrant", disabled: true

    box.vm.provision "shell" do |s|
      s.path = "freebsd.sh"
      s.name = "Provision"
      s.args = ["provision"]
    end
    box.vm.provision "shell", run: "always" do |s|
      s.path = "freebsd.sh"
      s.name = "Compile"
      s.args = ["compile"]
    end
  end

  config.vm.define "netbsd8" do |box|
    box.vm.box = "generic/netbsd8"
    box.ssh.shell = "sh"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    box.vm.provision "shell" do |s|
      s.path = "netbsd.sh"
      s.name = "Provision"
      s.args = ["provision"]
    end
    box.vm.provision "shell", run: "always" do |s|
      s.path = "netbsd.sh"
      s.name = "Setup"
      s.args = ENV['PR'] ? ["setup", ENV['PR']] : ["setup"]
    end
  end
end
